### ISSUE TITLE
Precisa do jQuery?

### ISSUE THREAD

**Issue by felipemfp** [theuves/dig#1]
Vi `$` no código, então precisa do jQuery?

**Comment by theuves** [comment]
Não, hehe, estava testando o *script* no *Chrome DevTool*, então estava usando-a, pois é mais curta (do que `documente.querySelector`). Ela não é do *jQuery*, e creio eu que funcione apenas no *Chrome*.

Vou mudá-la...

**Comment by felipemfp** [comment]
Aaah, show!
